on: [push]

jobs:
  composite_action_test:
    runs-on: ubuntu-latest
    name: A job to test composite actions
    steps:
      - uses: actions/checkout@v2
      - uses: tmadlener/composit_action_test@master
        with:
          greeted: 'Thomas the tester'
          substeps:
            - step1: Test step1
              run: echo "Hello"
            - step2: Test step2
              run: echo "Hello again"
